services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      secrets:
        - github_token

    container_name: alanwilliams-platform-frontend

    ports:
      - "5174:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    environment:
      NODE_ENV: development

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      secrets:
        - github_token

    container_name: alanwilliams-platform-backend

    ports:
      - "8081:8080"

    env_file:
      - ./backend/.env.local

    networks:
      - default
      - alanwilliams-backend

networks:
  alanwilliams-backend:
    external: true

secrets:
  github_token:
    environment: GITHUB_TOKEN