services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod

    restart: unless-stopped

    networks:
      - web

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    restart: unless-stopped

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      CLERK_ISSUER: ${CLERK_ISSUER}
      CLERK_AUTHORIZED_PARTIES: ${CLERK_AUTHORIZED_PARTIES}

    networks:
      - web
      - alanwilliams-backend

networks:
  web:
    name: ${COMPOSE_PROJECT_NAME}-web

  alanwilliams-backend:
    external: true